- path: Горящий Бензовоз.jpeg
  width: 600
  height: 600
  thumb: thumbnails_0.jpg?crc=171b7a47
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1620
  thumb_total_height: 324
- path: Один Дома.jpeg
  width: 600
  height: 600
  thumb: thumbnails_0.jpg?crc=171b7a47
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1620
  thumb_total_height: 324
- path: Радио-Т.jpg
  width: 640
  height: 640
  thumb: thumbnails_0.jpg?crc=171b7a47
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1620
  thumb_total_height: 324
- path: Что было раньше.jpeg
  width: 600
  height: 600
  thumb: thumbnails_0.jpg?crc=171b7a47
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1620
  thumb_total_height: 324
- path: Не занесли.jpeg
  width: 626
  height: 626
  thumb: thumbnails_0.jpg?crc=171b7a47
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1620
  thumb_total_height: 324
