- path: Горящий Бензовоз.jpeg
  width: 600
  height: 600
  thumb: thumbnails_0.jpg?crc=56c8be4d
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Один Дома.jpeg
  width: 600
  height: 600
  thumb: thumbnails_0.jpg?crc=56c8be4d
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Радио-Т.jpg
  width: 640
  height: 640
  thumb: thumbnails_0.jpg?crc=56c8be4d
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Что было раньше.jpeg
  width: 600
  height: 600
  thumb: thumbnails_0.jpg?crc=56c8be4d
  thumb_x: 972
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Не занесли.jpg
  width: 600
  height: 600
  thumb: thumbnails_0.jpg?crc=56c8be4d
  thumb_x: 1296
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Думаем Дальше.png
  width: 600
  height: 600
  thumb: thumbnails_0.png?crc=daec0cdc
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 972
  thumb_total_height: 324
- path: Завтракаст.png
  width: 600
  height: 600
  thumb: thumbnails_0.png?crc=daec0cdc
  thumb_x: 324
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 972
  thumb_total_height: 324
- path: Кабинет Лора.jpg
  width: 500
  height: 500
  thumb: thumbnails_0.jpg?crc=56c8be4d
  thumb_x: 1620
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 1944
  thumb_total_height: 324
- path: Горящий Бензовоз.png
  width: 1000
  height: 1000
  thumb: thumbnails_0.png?crc=daec0cdc
  thumb_x: 648
  thumb_width: 324
  thumb_height: 324
  thumb_total_width: 972
  thumb_total_height: 324
